-- Teal's Daily Fact Challenge v2.12.0
-- AWTRIX Top 10 integration foundation.
-- Run once after the earlier migrations.
--
-- Security design:
--   * The two new tables remain fully behind RLS with no browser policies.
--   * The clock receives only a preformatted rank + nickname string.
--   * Scores, times, PINs, student IDs, and teacher data are never returned.
--   * Public RPC access requires BOTH the project's publishable/anon API key
--     and a separate revocable X-AWTRIX-Token header whose SHA-256 hash is
--     stored in awtrix_clock_config.

create extension if not exists pgcrypto;

create table if not exists public.awtrix_clock_config (
    config_id smallint primary key default 1,
    block1_class_id uuid references public.classes(class_id) on delete set null,
    block2_class_id uuid references public.classes(class_id) on delete set null,
    block3_class_id uuid references public.classes(class_id) on delete set null,
    token_hash text,
    token_hint text,
    updated_at timestamptz not null default now(),
    constraint awtrix_single_config check (config_id = 1),
    constraint awtrix_token_hash_shape check (token_hash is null or token_hash ~ '^[0-9a-f]{64}$')
);

create table if not exists public.awtrix_clock_commands (
    command_id bigint generated by default as identity primary key,
    block_number smallint not null,
    requested_at timestamptz not null default now(),
    constraint awtrix_block_number_range check (block_number between 1 and 3)
);

create index if not exists awtrix_clock_commands_requested_idx
    on public.awtrix_clock_commands(command_id desc, requested_at desc);

alter table public.awtrix_clock_config enable row level security;
alter table public.awtrix_clock_commands enable row level security;

insert into public.awtrix_clock_config(config_id)
values (1)
on conflict (config_id) do nothing;

-- Internal helper. It may inspect private classroom data, but it returns only
-- the student-safe text that is allowed on the physical clock.
create or replace function public.awtrix_top10_payload_for_block(p_block integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_class_id uuid;
    v_class_name text;
    v_challenge_id uuid;
    v_count integer := 0;
    v_names text;
    v_text text;
begin
    if p_block not between 1 and 3 then
        return jsonb_build_object('ok', false, 'error', 'invalid_block');
    end if;

    select case p_block
        when 1 then block1_class_id
        when 2 then block2_class_id
        when 3 then block3_class_id
    end
    into v_class_id
    from public.awtrix_clock_config
    where config_id = 1;

    if v_class_id is null then
        return jsonb_build_object('ok', false, 'error', 'block_not_mapped', 'block', p_block);
    end if;

    select class_name
    into v_class_name
    from public.classes
    where class_id = v_class_id;

    select challenge_id
    into v_challenge_id
    from public.daily_challenges
    where challenge_date = (now() at time zone 'America/Indiana/Indianapolis')::date
    limit 1;

    if v_challenge_id is not null then
        with ranked as (
            select
                row_number() over (
                    order by da.correct_count desc, da.timed_seconds asc, da.completed_at asc
                ) as rank,
                s.nickname
            from public.daily_attempts da
            join public.students s on s.student_id = da.student_id
            where da.challenge_id = v_challenge_id
              and da.completed_at is not null
              and s.class_id = v_class_id
              and s.active = true
              and coalesce(s.is_test, false) = false
        ), top_rows as (
            select rank, nickname
            from ranked
            where rank <= 10
            order by rank
        )
        select
            count(*)::integer,
            string_agg('#' || rank::text || ' ' || nickname, '   ' order by rank)
        into v_count, v_names
        from top_rows;
    end if;

    if v_count > 0 then
        v_text := 'BLOCK ' || p_block::text || ' TOP 10!   ' || v_names;
    else
        v_text := 'BLOCK ' || p_block::text || ' TOP 10!   NO FINISHERS YET';
    end if;

    return jsonb_build_object(
        'ok', true,
        'block', p_block,
        'class_name', coalesce(v_class_name, 'Class'),
        'count', v_count,
        'text', v_text
    );
end;
$$;

revoke all on function public.awtrix_top10_payload_for_block(integer) from public;
revoke all on function public.awtrix_top10_payload_for_block(integer) from anon;
revoke all on function public.awtrix_top10_payload_for_block(integer) from authenticated;

create or replace function public.awtrix_top10(p_block integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_headers jsonb;
    v_token text;
    v_expected_hash text;
begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
    v_token := coalesce(v_headers ->> 'x-awtrix-token', '');

    select token_hash
    into v_expected_hash
    from public.awtrix_clock_config
    where config_id = 1;

    if v_expected_hash is null
       or v_token = ''
       or encode(digest(v_token, 'sha256'), 'hex') <> v_expected_hash then
        return jsonb_build_object('ok', false, 'error', 'unauthorized');
    end if;

    return public.awtrix_top10_payload_for_block(p_block);
end;
$$;

create or replace function public.awtrix_poll(p_after_id bigint default 0)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_headers jsonb;
    v_token text;
    v_expected_hash text;
    v_command_id bigint;
    v_block integer;
    v_latest_id bigint := 0;
    v_payload jsonb;
begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
    v_token := coalesce(v_headers ->> 'x-awtrix-token', '');

    select token_hash
    into v_expected_hash
    from public.awtrix_clock_config
    where config_id = 1;

    if v_expected_hash is null
       or v_token = ''
       or encode(digest(v_token, 'sha256'), 'hex') <> v_expected_hash then
        return jsonb_build_object('ok', false, 'error', 'unauthorized');
    end if;

    select coalesce(max(command_id), 0)
    into v_latest_id
    from public.awtrix_clock_commands;

    select command_id, block_number
    into v_command_id, v_block
    from public.awtrix_clock_commands
    where command_id > greatest(coalesce(p_after_id, 0), 0)
      and requested_at >= now() - interval '10 minutes'
    order by command_id desc
    limit 1;

    if v_command_id is null then
        return jsonb_build_object(
            'ok', true,
            'manual', false,
            'command_id', greatest(coalesce(p_after_id, 0), v_latest_id)
        );
    end if;

    v_payload := public.awtrix_top10_payload_for_block(v_block);
    return v_payload || jsonb_build_object(
        'manual', true,
        'command_id', v_command_id
    );
end;
$$;

revoke all on function public.awtrix_top10(integer) from public;
revoke all on function public.awtrix_poll(bigint) from public;
grant execute on function public.awtrix_top10(integer) to anon, authenticated;
grant execute on function public.awtrix_poll(bigint) to anon, authenticated;
